### ISSUE TITLE
Is is possible to use this plugin without a facebook account?

### ISSUE THREAD

**Issue by dimovnike** [dequis/purple-facebook#237]
The fb messenger android app allows this. Is this possble with this plugin?
Thanks.

**Comment by dequis** [comment]
Does it use something like username/password? If so, have you tried logging in with those details?

**Comment by dimovnike** [comment]
No, it uses only the phone number, it validates it with a SMS. But it definitely works with fb account disabled.

**Comment by dequis** [comment]
Looked at this, it's a handful of new requests and i'm not really sure how to allow both kinds of auth flows from the same username/password interface (phone numbers can be valid facebook account usernames too)

But, details aside, this is doable, just not high priority.

**Comment by marsjaninzmarsa** [comment]
Can you login to same SMS-activated account on multiple devices?

**Comment by TLATER** [comment]
> Looked at this

Are there any leftover notes from back then? I'd like to have a look myself.

**Comment by dequis** [comment]
Nothing on this but I have general notes on how to sniff the protocol at https://wiki.dequis.org/notes/facebook/

**Comment by dequis** [comment]
Also

>Can you login to same SMS-activated account on multiple devices?

This is a good question!

Does it work with, say, messenger.com? (it uses a completely different auth thing but it's a quick way to figure out how locked to the phone it's supposed to be)

**Comment by dequis** [comment]
There are four main requests involved

1. `b-api.facebook.com/method/user.sendMessengerOnlyPhoneConfirmationCode`
    * Sends a SMS to the phone
2. `b-api.facebook.com/method/user.confirmMessengerOnlyPhone`
    * User enters the confirmation code and it is sent here
3. `b-api.facebook.com/method/user.createMessengerOnlyAccount`
    * Returns access tokens for a newly created account.
4. `b-api.facebook.com/method/user.bypassLoginWithConfirmedMessengerCredentials`
    * Returns access tokens for an old account, if it considers it can be "recovered"

The 2nd request may lead to the 3rd or the 4th, depending on the result. Usually it replies with this:

```json
{
    "account_id": "",
    "is_partial": false,
}
```

If an account exists and some other conditions are met (same device, probably), it asks you "is this you?" and lets you recover the account.

```json
{
    "account_id": "",
    "is_partial": false,
    "recovered_messenger_account": {
        "account_id": "[LONG BASE64-LIKE STRING]",
        "firstname": "dx",
        "is_messenger_only": true,
        "is_twofac_user": false,
        "lastname": "Dx",
        "profilepic": "[...]"
    }
}
```

Otherwise, it creates a new account with the same phone number, and "blocks" the previous one in a very interesting way - the account still exists but you can only talk to contacts you already have:

```json
{
  "error": {
    "code": 1404137,
    "api_error_code": null,
    "summary": "Messenger Only account with no phone number blocked from cold contact",
    "description": "Your account's phone number has been confirmed by another
        Messenger account. You cannot initiate threads with people that do not
        have you as a contact.",
    "...": "...",
    }
}
```

(This message is not shown anywhere in the UI)

Anyway, it doesn't seem like you can have multiple devices. Also, messenger.com doesn't take logins for those. We might need to guess the unguessable device ID to be able to recover an account. Otherwise we have to create an account on every login. That would mean blocking previously created accounts under the same number, to end up with an empty contact list (and no way to add contacts)

Implementing this is a terrible idea. So I'm closing this. Sorry for that.

**Comment by kedarv** [comment]
@dequis do you happen to have the full curls with headers/body info to login successfully as a phone only account? I'm working on building out something similar to this library and if things were already specced out that would be greatly helpful.
