### ISSUE TITLE
User must verify their account www.facebook.com (Error 405)

### ISSUE THREAD

**Issue by suleiman-m** [dequis/purple-facebook#278]
I am getting this error when trying to connect to Facebook, and I went all over the security settings, have my phone set-up, got generated codes etc. but I am unsure of how to verify my own account. Does anyone know how I can do what the error is saying?

**Comment by dequis** [comment]
Are you using pidgin or something like spectrum?

**Comment by suleiman-m** [comment]
I'm using the Colloquy IRC with bitlbee-facebook. I can create accounts and turn them "on" as well, but when I do it with my Facebook the root just responds with this Error 405. And then it keeps trying to log-in after increasing intervals (i.e. 5s, 10s, 15s, 45s, etc.)

**Comment by dequis** [comment]
Then go over here https://github.com/bitlbee/bitlbee-facebook/issues/108

**Comment by linuxrocks123** [comment]
I'd like to reopen this issue because I'm using Spectrum, which uses purple-facebook, and am constantly running into this error.  Every 24 hours, Facebook says I've been hacked and have to reset my Facebook password.  Very annoying, and I'm pretty sure they're wrong and it has something to do with Spectrum and therefore purple-facebook.  Please let me know if I can provide any helpful information or if this is the wrong place to report the issue, and thanks for your work on purple-facebook; it's a great project.

**Comment by dequis** [comment]
@linuxrocks123 #282

**Comment by MannyPaige** [comment]
It says I have to verify my account, how am I supposed to do that if it won't explain it to me??

**Comment by dequis** [comment]
Usually, by going to www.facebook.com and logging in.

Also, please open a new issue instead of posting to old closed ones.
