### ISSUE TITLE
Secret Conversation support?

### ISSUE THREAD

**Issue by fritzophrenic** [dequis/purple-facebook#314]
I've read that Facebook Messenger uses the Signal protocol to enable end-to-end encryption in their "Secret Conversation" feature. Is there any possibility Secret Conversation support could be added to purple-facebook?

**Comment by dequis** [comment]
Sorry, but I have no plans to implement this any time soon.

As I have stated [elsewhere][1] I'm very reluctant to implement complex encryption features by myself, particularly if there's no one else to help if implementation issues arise. This was a problem when i had to maintain code that uses libotr, a high-level library with a relatively simple API, and it was a problem with XMPP's OMEMO, a properly documented protocol with plenty of existing open source implementations, but no directly usable high-level library, only libsignal-protocol which requires you to deal with low-level details (unlike libsignal-service which is a complete implementation of the messaging protocol used by the signal mobile app, but isn't usable for OMEMO or fb secret chats).

Implementing facebook secret chats is, at least in theory, similar in complexity to implementing OMEMO - libsignal-protocol exists, and one has to deal with it the parts specific to the messaging protocol, which is facebook's protocol instead of XMPP. This means reverse engineering the signaling layer to establish encrypted sessions. Hopefully that's a direct translation of other more public protocols, but even if it was, it's not trivial. And there's a high chance it isn't. Then there's the handling of persistence / long-term keys, etc, and who knows what else I'm not considering.

If I decided to spend the 100 hours (made up number) required to implement this, it would still result in more time with user support and dealing with weird edge cases which will definitely appear. That is also one of the reasons I'm not saying "patches welcome". No thanks. I have enough projects to maintain.

So forget about all of this and just use this OMEMO plugin with XMPP: https://github.com/gkdr/lurch/

[1]: https://bugs.bitlbee.org/ticket/1239

**Comment by marsjaninzmarsa** [comment]
It should probably be implemented as separate Pidgin plugin, if implemented at all. Required interface and complexity is too much for purple plugin.

Please also notice that Facebook allows encrypted chats only from (or rather to) one device at a time, it stores only single encryption key per contact, key is not transferable between devices and selecting another device implicits key regeneration and invalidation of all pending messages.

You should ask yourself if you really need Pidgin to be that selected device, without easy "temporary switch to another" option, and with risk of lost messages in case of another Facebook protocol change. Especially when you have other e2e encryption solutions, more mature ones, better designed for desktop user flow.
