### ISSUE TITLE
Empathy ? Fedora repository ?

### ISSUE THREAD

**Issue by Nicryc** [dequis/purple-facebook#315]
Hello,
Does this plugin work with Empathy ? Because I couldn't connect.
Something else, I downloaded it from the official repository of Fedora, but the version number is weird. Is it still up to date there ?
Thank.

**Comment by dequis** [comment]
It probably works with empathy. It would help if you mentioned the error messages you get.

>but the version number is weird

It would help if you mentioned the version number itself.

**Comment by Nicryc** [comment]
The version number : 
Version     : 0.0.0.20160409
Révision    : 0.4.git66ee773.fc25

I don't have a specific error with Empathy it just don't connect.
Either it says « Disconnected – No reasons indicated » or « Disconnected – Authentication failed »

**Comment by dequis** [comment]
The second version number doesn't look like anything that makes sense to me. The first one is just a timestamp from one year ago. You need to upgrade to the latest version.

You'll have to complain to whoever you got the package from, or follow the instructions to build from source https://github.com/dequis/purple-facebook/wiki/Building-on-*NIX

**Comment by Nicryc** [comment]
Ok so the package has been updated in the Fedora repository but it still doesn't work with Empathy. Don't understand why. Same error than above.

**Comment by dequis** [comment]
I have no experience with that client at all, I just know it worked for other people. Please install pidgin temporarily and try it there to ensure it's not an issue with your plugin version. Otherwise, I don't know, ask the Empathy devs. Oh also, ensure you're not actually using "Facebook (XMPP)", that would be an older thing.

**Comment by Nicryc** [comment]
I've checked on Pidgin and it works perfectly. 
On Empathy there is only one option which is « Facebook Chat ». There is no « Facebook (XMPP) ». Maybe I do something wrong but I don't think. I tried with my email, my user name and my phone number. With the two latter it tries to connect but fail and with the former it doesn't even try to connect.

**Comment by dequis** [comment]
Went ahead and wasted some time on this nonsense. Telepathy is a bloody mess. Took me way too long to figure out which one of their 50 components is the relevant one. And it turned out to be "telepathy-account-widgets" which isn't even listed as a component in most places, and is embedded as a submodule in empathy (which supposedly isn't managed by the same people? I don't even know)

Anyway, https://bugzilla.gnome.org/show_bug.cgi?id=747623 fixes it by removing this:

```c
368           if (!tp_strdiff (cm_name, "haze") &&
369               !tp_strdiff (proto_name, "facebook"))
370             /* Facebook now supports XMPP so drop the purple facebook plugin; user
371              * should use Gabble */
372             continue;
```

This change happened a couple of months ago is not in any stable empathy release as far as I can see. You need a git version of empathy and/or telepathy-account-widgets
