### ISSUE TITLE
Connection error on 0x55b166830e00 (reason: 0 description: Failed to read fixed header)

### ISSUE THREAD

**Issue by jshand2015** [dequis/purple-facebook#444]
Hi there, this issue in caption only started happening about 3 days ago.  is there a bug with your plugin or facebook itself.  this plugin before this error started, i didn't have any problems connecting and chatting with facebook friends.  can you please investigate?
[purple-debug.log](https://github.com/dequis/purple-facebook/files/2541388/purple-debug.log)

**Comment by Zombie-Ryushu** [comment]
I get an error like this every time now.

**Comment by petermolnar** [comment]
same here; only since today. 
`connection: Connection error on 0x5586fa2a3580 (reason: 0 description: Failed to read fixed header)`

If it's related to #410 the NSS plugin tweaks didn't help, neither did updating (`./autogen.sh`) and recompiling the `wip-work-chat` branch :(

I have an SSO Workplace horror, and I'm willing to help/debug/test as much as needed.

**Comment by dequis** [comment]
Yeah, see #410 and upgrade to 0.9.6
